# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "demo-app"
client_id = "c706ad5a238fac0609b0078d8789cd55"
application_url = "https://current-factual-bluegill.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://current-factual-bluegill.ngrok-free.app/authenticate"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "ostad-store-dev-1.myshopify.com"
